spring:
  application:
    name: omni-store-user-service

  datasource:
    url: jdbc:${SGBD}://${POSTGRES_USER_SERVICE}:${POSTGRES_USER_PORT}/${POSTGRES_USER_DB}
    username: ${POSTGRES_USER_USERNAME}
    password: ${POSTGRES_USER_PASS}
    driver-class-name: ${SGBD_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${SGBD_DIALECT}

server:
  port: 8081
